sudo: false
language: rust

addons:
    apt:
        sources:
            - debian-sid
        packages:
            - gcc-arm-none-eabi

# TODO: use rustup to pin version?
rust:
    - nightly

script: cargo build --verbose --target thumbv7m-none-eabi

after_success:
    - cargo doc
    - ./scripts/ghp_upload.sh
