sudo: false
language: rust

# TODO: use rustup to pin version?
rust:
    - nightly

script: cargo build --verbose --target thumbv7em-none-eabi

after_success:
    - cargo doc
    - ./scripts/ghp_upload.sh
