sudo: false
language: rust

addons:
    apt:
        sources:
            - debian-sid
        packages:
            - gcc-arm-none-eabi

# TODO: use rustup to pin version?
rust:
    - nightly

script:
    - make release
    - make symtab
    - make info

after_success:
    - cargo doc
    - ./scripts/ghp_upload.sh
