(function() {var implementors = {};
implementors["aster"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='aster/invoke/struct.Identity.html' title='aster::invoke::Identity'>Identity</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='aster/struct.AstBuilder.html' title='aster::AstBuilder'>AstBuilder</a>",];implementors["dynamo"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='dynamo/parser/enum.StaticValue.html' title='dynamo::parser::StaticValue'>StaticValue</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='dynamo/ioreg/common/enum.FunctionType.html' title='dynamo::ioreg::common::FunctionType'>FunctionType</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='dynamo/mcu/common/struct.ActionInfo.html' title='dynamo::mcu::common::ActionInfo'>ActionInfo</a>",];implementors["peregrine"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='peregrine/mcus/cortexm4/core/fpu/struct.Access.html' title='peregrine::mcus::cortexm4::core::fpu::Access'>Access</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='peregrine/mcus/cortexm4/core/fpu/struct.Unit.html' title='peregrine::mcus::cortexm4::core::fpu::Unit'>Unit</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='peregrine/mcus/cortexm4/core/systick/struct.SysTick.html' title='peregrine::mcus::cortexm4::core::systick::SysTick'>SysTick</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='peregrine/mcus/cortexm4/kinetis/k64/wdog/struct.Watchdog.html' title='peregrine::mcus::cortexm4::kinetis::k64::wdog::Watchdog'>Watchdog</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='peregrine/mcus/cortexm4/kinetis/k64/struct.K64NVIC.html' title='peregrine::mcus::cortexm4::kinetis::k64::K64NVIC'>K64NVIC</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='peregrine/mcus/cortexm4/kinetis/k64/struct.K64.html' title='peregrine::mcus::cortexm4::kinetis::k64::K64'>K64</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
